apiVersion: v1
kind: Service
metadata:
  name: {{ include "sampleapp.fullname" . }}
  labels:
    {{- include "sampleapp.labels" . | nindent 4 }}
    annotations:
    # This tells Prometheus that it should scrape this service for metrics
    prometheus.io/scrape: "true"
    # This tells Prometheus which port the metrics are exposed on
    prometheus.io/port: "{{ .Values.service.port }}"
    # This tells Prometheus the specific path of your metrics endpoint
    prometheus.io/path: /metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sampleapp.selectorLabels" . | nindent 4 }}
