{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sampleapp.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "sampleapp.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}
