name: List Minikube Pods

on:
  workflow_dispatch:

jobs:
  list-pods:
    runs-on: self-hosted

    # 🔑 Launch every step with ExecutionPolicy=Bypass
    defaults:
      run:
        # {0} is where GitHub inserts the temp script path
        shell: powershell -NoProfile -ExecutionPolicy Bypass -Command "& {0}"

    steps:
      - name: Show current execution policy (for proof)
        run: Get-ExecutionPolicy -List   # will show Bypass for Process

      - name: Ensure Minikube is running
        run: |
          minikube status || minikube start

      - name: Point kubectl at Minikube
        run: kubectl config use-context minikube

      - name: List all pods
        run: kubectl get pods --all-namespaces
