name: List Minikube Pods

on:
  workflow_dispatch: # You can also use push/pull_request/etc

jobs:
  list-pods:
    runs-on: self-hosted

    steps:
      - name: Allow unsigned PowerShell scripts (for this session only)
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
      
      - name: Check Minikube status
        shell: pwsh
        run: |
          minikube status

