name: Build‑Push‑Deploy to Minikube (PowerShell)

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    permissions: { packages: write, contents: read }

    defaults:
      run:
        shell: powershell -NoProfile -ExecutionPolicy Bypass -Command "& {0}"

    env:
      MINIKUBE_HOME: 'C:\Users\Bar-DesktopNG\.minikube'
      KUBECONFIG:    'C:\Users\Bar-DesktopNG\.kube\config'
      TAG: ${{ github.run_number }}

    steps:
      - name: Check Minikube status
        run: minikube status

      - name: kubectl connectivity
        run: kubectl get nodes

      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} |
          docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/sample-nodejs:${{ env.TAG }} .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/sample-nodejs:${{ env.TAG }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install sample-nodejs .\chart `
            --set image.repository=ghcr.io/${{ github.repository_owner }}/sample-nodejs `
            --set image.tag=${{ env.TAG }} `
            --set image.pullPolicy=IfNotPresent
